# README
# Phillip Long
# May 11, 2023

# This script is meant to, given a list of accounts, initiate contact via DM to these accounts.

# python ~/finding_a_roommate/initiate_contact.py driver_address username password accounts_to_dm

# driver_address = filepath to Selenium Chrome Web Driver, download at: https://chromedriver.chromium.org/downloads
# username = Instagram username
# password = Instagram password
# accounts_to_dm = filepath to list of Muir accounts generated by find_accounts.py


# IMPORTS
from login import instagram_driver # my own class that logs into instagram for me while creating a driver
import sys # for stdin arguments
from os.path import exists # for checking if files exist
from os.path import dirname # for determining the output file

# ARGUMENTS
# sys.argv = ("bot.py", "/Users/philliplong/Desktop/Coding/chromedriver", "", "", "/Users/philliplong/Desktop/Coding/finding_a_roommate/outputs/accounts_muir.txt")
sys.argv = ("bot.py", "/Users/philliplong/Desktop/Coding/chromedriver", "jcreek_rec", "phillip5143", "/Users/philliplong/Desktop/Coding/finding_a_roommate/outputs/accounts_muir.txt")
driver_address = sys.argv[1] # driver_address
username = sys.argv[2].replace("@", "") # username, remove @ symbol if included
password = sys.argv[3] # password
accounts_muir_output = sys.argv[4] # accounts_to_dm


# CREATE DRIVER AND LOGIN
driver = instagram_driver(driver_address = driver_address, username = username, password = password) # create instance of chrome driver
driver.login()

# CLICK ON DM BUTTON
driver.click_messages()


# READ IN FILES, CREATE SETS
accounts_muir = set(()) # set of accounts that mention muir (no duplicates)
if exists(accounts_muir_output):
    for line in open(accounts_muir_output):
        accounts_muir.add(str(line).strip())

accounts_initiated_contact = set(()) # set of accounts that the program might have initiated contact with (no duplicates)
accounts_initiated_contact_output = dirname(accounts_muir_output) + "/accounts_initiated_contact.txt"
if exists(accounts_initiated_contact_output):
    for line in open(accounts_initiated_contact_output):
        accounts_initiated_contact.add(str(line).strip())
        
accounts_to_dm = set((account for account in accounts_muir if account not in accounts_initiated_contact))


# DM ACCOUNTS
message = ""
first_account_to_dm = True
for account in accounts_to_dm:
    try:
        
        # CLICK ON NEW MESSAGE ICON
        driver.driver.find_element("xpath", "//button[@class='_abl- _abm2']").click()
        driver.wait(2, 4.5)
        
        # ENTER ACCCONT NAME
        driver.simulate_typing(element = driver.driver.find_element("xpath", "//input[@name='queryBox'][@placeholder='Search...']"),
                               text = account)
        driver.wait(1, 2)

        # SELECT ACCOUNT TO DM
        driver.driver.find_element("xpath", f"//span[@class='x1lliihq x193iq5w x6ikm8r x10wlt62 xlyipyv xuxw1ft'][text()='{account}']").click()
        driver.wait(1, 1.5)
        
        # CLICK ON NEXT BUTTON
        driver.driver.find_element("xpath", "//button[@class='_acan _acao _acas _acav _aj1-']/div[text()='Next']").click()
        driver.wait(4, 5)
        
        # LOCATE TEXT BOX, TYPE IN MESSAGE
        if first_account_to_dm: # if first iteration, type out the message slowly
            scalar = 3.0
            first_account_to_dm = False # update boolean
        else: # not the first iteration
            scalar = 0.0

        driver.simulate_typing(element = driver.driver.find_element("xpath", "//textarea[@placeholder='Message...']"),
                               text = message, scalar = scalar)
        driver.wait(1, 2)
        
        # SEND MESSAGE
        driver.driver.find_element("xpath", "//div[@class='x1i10hfl xjqpnuy xa49m3k xqeqjp1 x2hbi6w xdl72j9 x2lah0s xe8uvvx xdj266r x11i5rnm xat24cr x1mh8g0r x2lwn1j xeuugli x1hl2dhg xggy1nq x1ja2u2z x1t137rt x1q0g3np x1lku1pv x1a2a7pz x6s0dn4 xjyslct x1ejq31n xd10rxx x1sy0etr x17r0tee x9f619 x1ypdohk x1i0vuye xwhw2v2 xl56j7k x17ydfre x1f6kntn x2b8uid xlyipyv x87ps6o x14atkfc x1d5wrs8 x972fbf xcfux6l x1qhh985 xm0m39n xm3z3ea x1x8b98j x131883w x16mih1h xt0psk2 xt7dq6l xexx8yu x4uap5 x18d9i69 xkhd6sd x1n2onr6 xjbqb8w x1n5bzlp x173jzuc x1yc6y37'][@role='button']").click()
        driver.wait(2, 3)
        
        accounts_initiated_contact.add(account)


    except:
        driver.wait(3, 4) # if for some reason the account doesn't exist anymore or something, wait, and move on
        continue
        

# WRITE THE ACCOUNTS TO WHICH PROGRAM HAS INITIATED CONTACT TO FILE
accounts_initiated_contact_writable = open(accounts_initiated_contact_output, "w")
accounts_initiated_contact_writable.write("\n".join(accounts_initiated_contact))
accounts_initiated_contact_writable.close()